version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - echo Build started on `date`
      - mvn test 
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
      - tar cvf my-app.tar target  appspec.yml
artifacts:
  files:
    - my-app.tar    
  discard-paths: yes
